### ISSUE TITLE
Need a new release to PyPI

### ISSUE THREAD

**Issue by cclauss** [ggtracker/sc2reader#109]
https://github.com/ggtracker/sc2reader/issues/108#issuecomment-570013349 and drop all legacy Python support.

**Comment by StoicLoofah** [comment]
Thanks for pointing this out. Yes, a new release would address the 4.11 replays issue.

Regarding dropping legacy Python support, is it sufficient for now to just to remove references to python2 in `setup.py`? I think we have a lot of compatibility references in the code, but I have to admit that I'm not particularly interested in spending the time to clean all of that up.

**Comment by cclauss** [comment]
__pip install pyupgrade ; pyupgrade --py3-plus__

https://github.com/asottile/pyupgrade

**Comment by StoicLoofah** [comment]
See #85  about dropping legacy support
