### ISSUE TITLE
Recognizing Server Location in Ladder/Online Games

### ISSUE THREAD

**Issue by benjaminmesser** [ggtracker/sc2reader#113]
I was just wondering if it is possible to find which server a game was played on (Americas/EU/Korea) through replay data. Ideally, I would like to be able to determine the server for any game (including custom games, arcade games, and campaign), but I would be satisfied if I was able to get this information just for ladder games, vs AI, and co-op. If this is not possible through replay data then is there any other way that one might obtain this information?

**Comment by Talv** [comment]
Yes, this information is available here:
https://github.com/ggtracker/sc2reader/blob/c0bf9a9fead061347e034ffd89dec5841d2e0bd2/sc2reader/resources.py#L132-L133

Behind the scenes it is determined from battle.net identifier of a player.
https://github.com/ggtracker/sc2reader/blob/c0bf9a9fead061347e034ffd89dec5841d2e0bd2/sc2reader/objects.py#L130-L132
https://github.com/ggtracker/sc2reader/blob/c0bf9a9fead061347e034ffd89dec5841d2e0bd2/sc2reader/constants.py#L63
Thus this method also applies to https://github.com/Blizzard/s2protocol/issues/104

**Comment by benjaminmesser** [comment]
Thank you very much, that is exactly the kind of thing I was hoping to find. Out of curiosity, does the "toon_id" parameter have any meaning or is that just some random seeded number? Thanks again.

**Comment by Talv** [comment]
It's not random by any means. It is unique number that corresponds to battle.net profile/character. Such profile is bound to the region, so player using the same account will have different profile in each region.

Also, these parameters can be used to link to an online profile:
https://github.com/ggtracker/sc2reader/blob/1fd0b6a7f97de11d579a005940c438076db8eba6/sc2reader/objects.py#L255-L258

`toon_id` is also an incremental ID, thus it gives possibility to estimate how long ago the profile was created.
