### ISSUE TITLE
List of mapping: Unit name to Unit types

### ISSUE THREAD

**Issue by BurnySc2** [ggtracker/sc2reader#115]
I'd like to know if the unit mapping (unit name to unit type number) are somewhere listed.

The bot APIs for StarCraft 2 use the IDs from the stableid.json file: https://github.com/BurnySc2/python-sc2/blob/develop/sc2/ids/unit_typeid.py#L26

However, when parsing replays with a debugger attached, I can see that the type `CommandCenter` has type `39`, however in the stableid.json it is listed as id `18`.

Is there a list somewhere so I can create a mapping between these two?

**Comment by StoicLoofah** [comment]
I think this data might change depending on the datapack, but I think this is the latest version we have

https://github.com/ggtracker/sc2reader/blob/c0bf9a9fead061347e034ffd89dec5841d2e0bd2/sc2reader/data/LotV/77379_units.csv

Is this what you were looking for?

**Comment by BurnySc2** [comment]
Yes thank you! That is exactly what I needed.
Sorry for creating an issue just for this question.

Btw I'm trying to grab the building placement from pro-replays to be able to let my SC2 bot use the same building positions.

**Comment by StoicLoofah** [comment]
No problem. Good luck!
