### ISSUE TITLE
Issue parsing new replays 

### ISSUE THREAD

**Issue by GoldwinXS** [ggtracker/sc2reader#141]
Hey there!  
When trying to load up a ladder replay from yesterday I get:

```
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5005
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5005
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3020
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3020
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5200
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5200
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3016
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3016
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5300
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5300
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5002
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5002
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3019
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3019
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5004
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5004
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5003
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5003
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5001
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5001
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3017
INFO:sc2reader.objects.Attribute:Unknown attribute id: 3017
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5000
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5000
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5100
INFO:sc2reader.objects.Attribute:Unknown attribute id: 5100
```

I found that I can get it to work with "load_level=0", but nothing past that will work.

(btw: love the project!)

**Comment by StoicLoofah** [comment]
@GoldwinXS Thanks for reporting this and using the project!

Can you share the replay causing the problems?

I suspect that we need to grab fresh data, but that would need to be verified. The steps for doing it are at https://github.com/ggtracker/sc2reader/blob/c2a5407cb13fc41e2b44af07ae2a7ba48ffb7695/sc2reader/data/HOWTO.md if you want to take a shot

**Comment by Talv** [comment]
The attached log doesn't show any problems. `Unknown attribute` is merely a warning. And listed IDs are totally irrelevant. At least for melee/arcade maps. Most of these unknowns relate to the coop mode.

For instance:
`attribute id: 5000` = `Commander Mastery Talent`
`attribute id: 3017` = `Commander Mastery Tier`
And some of these appear to be duplicates - according to my reference at least (<https://sc2arcade.com/map/1/2/> & <https://sc2arcade.com/map/1/1/> <https://sc2arcade.com/map/1/305119/>). `5000` is the same thing as `5001` etc.

**Comment by GoldwinXS** [comment]
@Talv This is odd. I never play coop- only ladder. And I picked a replay from yesterday. 

I tested a few files before I made this issue, so I was pretty confident there was one. I just tried opening each replay in my replay folder and it looks like it's all working now.

I'm not at all sure how that happened.. I haven't changed anything on my end.

Thanks for the assistance on this! I'm glad it's working.

**Comment by Talv** [comment]
These attributes, while exclusive to coop mode can also appear in any SC2Replay, it's just that they don't hold any value in case of 1v1 mode etc. That's why these warnings/notices mean nothing, and can be safely ignored.

Ideally they should've been mapped by `sc2reader` (which would also suppress them from appearing in the log), it's just that no one needed that yet so it has stayed unimplemented.
