### ISSUE TITLE
sc2reader 1.6.0 from PIP unable to load_replay

### ISSUE THREAD

**Issue by Andrene** [ggtracker/sc2reader#142]
As the title suggests installing sc2reader 1.6.0(current version) with pip results in a keyerror when using load_replay(Python 3.8/3.9 were what I tested).
Resolved this by cloning the current master branch and popping that into the place of the broken version.
Is it possible to create a new release with the current changes, or are there more things needed before a new release should be created?

**Comment by StoicLoofah** [comment]
Apologies for the delay, but I just marked a 1.7.0 release with the changes from the master branch in it. Can you give it a spin? Feel free to close if it works for you!

**Comment by Andrene** [comment]
Worked for me! Ill mark this as closed now.
