### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [ggtracker/sc2reader#145]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine docs/source/articles/creatingagameengineplugin.rst, sc2reader/engine/engine.py and observe `aggrated`, however expect to see `aggregated`.
- Examine sc2reader/objects.py and observe `acount`, however expect to see `account`.
- Examine docs/source/tutorials/prettyprinter.rst and observe `versitile`, however expect to see `versatile`.
- Examine docs/source/articles/whatsinareplay.rst and observe `unncessary`, however expect to see `unnecessary`.
- Examine sc2reader/events/game.py and observe `targetting`, however expect to see `targeting`.
- Examine examples/sc2autosave.py and observe `substition`, however expect to see `substitution`.
- Examine sc2reader/resources.py and observe `requirments`, however expect to see `requirements`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/sc2reader/pull/new/bugfix_typos

Thanks.

**Comment by cclauss** [comment]
How are these typos being missed by codespell running in our automated tests?
https://github.com/ggtracker/sc2reader/blob/upstream/.circleci/config.yml#L20

**Comment by StoicLoofah** [comment]
@timgates42 Would be great if you could open a PR for it! 

@cclauss Great question about codespell. I feel like it has corrected other typos in the past, so it's working to some degree

**Comment by timgates42** [comment]
Thanks @StoicLoofah raised #146

**Comment by cclauss** [comment]
@timgates42 You might consider contributing some of these off-by-just-one-letter fixes to codespell.  Especially the _account_ one might be done in other repos.

**Comment by timgates42** [comment]
Yeah that is a great idea @cclauss - Thanks!

**Comment by timgates42** [comment]
Interestingly @cclauss acount was added back in 2018 - https://github.com/codespell-project/codespell/commit/3f94316a04d7074e54bbfd6328323db15d0af193

**Comment by timgates42** [comment]
In fact only 2 from this list were missing in the latest version - https://github.com/codespell-project/codespell/pull/2019

**Comment by cclauss** [comment]
“Small moves.”  -- [_Contact_](https://www.imdb.com/title/tt0118884)

Thanks for doing this.
