### ISSUE TITLE
timestamps of replay.events don't match the times of the actual actions in the replay files

### ISSUE THREAD

**Issue by bw-leran** [ggtracker/sc2reader#155]
I've tested this out with a couple different files now. I'm printing out each event in replay.events, but when double checking the events against the actual replay file (meaning I'm actually watching a .SC2Replay file and checking what time things are occuring in the replay then comparing that to the timestamps from replay.events) the times aren't exactly matching up. For example, replay.events says that a refinery is built at 17 seconds, but I can clearly see that it is built at 13 seconds. The actions are accurate, but the times seem to be off. Is this normal? Or am I loading the replay file incorrectly?

Here is how I'm loading the replay file:

replay = sc2reader.load_replay(replay_file,engine=sc2reader.engine.GameEngine(plugins=[ContextLoader(),APMTracker(), SelectionTracker()]))

**Comment by Andrene** [comment]
It looks like this may be related to #130 as doing (17*16)/22.4 puts it in the correct ballpark (guessing its not closer to 13 due to those times being just seconds and not factoring in decimal values)

**Comment by bw-leran** [comment]
@Andrene thanks for linking that issue. That solution seems to be much more accurate. I was using general terms with seconds, I'm using the actual frames to get the exact time to include decimal values.
