### ISSUE TITLE
Cannot compile documentation (sphinx.ext.pngmath is deprecated)

### ISSUE THREAD

**Issue by dragokas** [ggtracker/sc2reader#157]
When attempt to run:
```
docs/make.bat html
```
```
exception: No module named 'sphinx.ext.pngmath'
```
See: https://github.com/sphinx-doc/sphinx/issues/6182

**Comment by StoicLoofah** [comment]
@dragokas can you confirm whether the branch below fixes your problem?

**Comment by dragokas** [comment]
Build is success using @cclauss branch.
