### ISSUE TITLE
How to Use the Tracker Events?

### ISSUE THREAD

**Issue by windowshopr** [ggtracker/sc2reader#169]
Looking at the documentation for, say, PlayerStatsEvent , all I see is:

```
class sc2reader.events.tracker.PlayerStatsEvent(frames, data, build)
Player Stats events are generated for all players that were in.....
```
...but no description of the data types for the parameters, or example on how to use it. Can someone point me in the appropriate direction? Would love to see what kind of data gets returned in these trackers. I was looking through the code for the Trackers as well, but it still wasn't super clear to me. An example usage from a replay file would be awesome! Thanks!

**Comment by StoicLoofah** [comment]
You can glance through the code at https://github.com/ggtracker/sc2reader/blob/b9caad908e3ebc0c1a5df3bac90d703610b56acd/sc2reader/events/tracker.py#L70

to see what properties get stored in the PlayerStats

As a rough proxy, I think the data here is in general similar to what appears as part of the observer panel in-game.
