### ISSUE TITLE
KeyError 38 while parsing an s2gs

### ISSUE THREAD

**Issue by dsjoerg** [ggtracker/sc2reader#2]
File is 9fd34a64b68c8d8150f59a3c6d87e227ab0cc3d7fe5b8f9d8e403de173fdce29.s2gs, obtainable from depot.

Not sure if it's the EU or US depot, though.   Marian, can you tell?

http://ec2-54-243-214-243.compute-1.amazonaws.com/resque/statuses/67895980fad2012fbe8522000a1dea5f

**Comment by dsjoerg** [comment]
Added a failing test to ggpyjobs for this.

**Comment by GraylinKim** [comment]
Okay, this is a localization issue. Specifically, map makers from other localities aren't filling in their `enUS` localizations. This causes sheet and key errors when we go to do the mappings. In this case:

```
zhCN 5
ruRU 5
plPL 5
esES 5
enGB 8
frFR 5
enUS 5
koKR 5
zhTW 5
itIT 5
esMX 5
ptBR 5
deDE 5
```

We can see that the primary language of the author was `enGB` and other localizations only have the default SC2 mappings. All the missing keys and sheets are available in the 'enGB' localization.

So the question is, how do you want to resolve this?

I can use the localization with the highest sheet/key count, favoring `enUS` in a tie. Or would you prefer to just stick to our `enUS` guns? I suppose there could also be some fallback strategy where `enUS` is used when possible but that might lead to mixed language results.

**Comment by dsjoerg** [comment]
When a map is missing enUS localizations, how about sc2reader throw a NoInglesException.  ggpyjobs can catch that and it will handle it by silently moving on.  Maps without enUS are not important to ggtracker for the forseeable future.

**Comment by GraylinKim** [comment]
Fixed by f7d5bf10a2950269cd5cd4bead61f3d74dfce8cd

``` python
>>> import sc2reader
>>> sc2reader.load_game_summary('9fd34a64b68c8d8150f59a3c6d87e227ab0cc3d7fe5b8f9d8e403de173fdce29.s2gs')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sc2reader/factories.py", line 92, in load_game_summary
    return self.load(GameSummary, source, options, **new_options)
  File "sc2reader/factories.py", line 137, in load
    return self._load(cls, resource, filename=filename, options=options)
  File "sc2reader/factories.py", line 147, in _load
    obj = cls(resource, filename=filename, factory=self, **options)
  File "sc2reader/resources.py", line 747, in __init__
    self.load_translations()
  File "sc2reader/resources.py", line 833, in load_translations
    raise SC2ReaderLocalizationError(msg.format(self.opt.lang,sheet,item))
sc2reader.exceptions.SC2ReaderLocalizationError: No enUS translation for sheet 3, item 38
>>> 
```

I'm not sure how you wanted to handle this exception in ggpyjobs though. Is the patch below what you had in mind?

``` diff
diff --git a/sc2parse/sc2reader_to_esdb.py b/sc2parse/sc2reader_to_esdb.py
index ff516ac..aafc26b 100644
--- a/sc2parse/sc2reader_to_esdb.py
+++ b/sc2parse/sc2reader_to_esdb.py
@@ -17,6 +17,7 @@ from boto.s3.key import Key
 from models import *
 from django.conf import settings

+from sc2reader.exceptions import SC2ReaderLocalizationError
 from sc2parse import ggfactory
 from sc2parse.plugins import ARMY_INFO, MAX_NUM_UNITS

@@ -309,7 +310,12 @@ class SC2ReaderToEsdb():
       """main entry point for s2gs processing."""
       job.set_status(status='working', num=0, message='Reading s2gs file')
       hash = hashlib.sha256(stringio.getvalue()).hexdigest()
-      summary = ggfactory.load_game_summary(stringio)
+      try:
+          summary = ggfactory.load_game_summary(stringio)
+      except SC2ReaderLocalizationError as e:
+          # TODO:  Do we need to do any job status clean up here?
+          print "Localization error for s2gs hash {0}. No big deal. {}".format(hash, sys.exec_info()[0])
+          return None

       job.set_status(num=25, message = 'Saving summary details')
       matchSummaryDB = self.getMatchSummaryDB(summary, hash)
```

**Comment by dsjoerg** [comment]
Perfect!

**Comment by GraylinKim** [comment]
In the spirit of "we'd like to parse as much as possible without freaking out and dying when we encounter something we can't handle unless we know it's a ladder game" I am going to revert this patch.

Instead of throwing exceptions, sc2reader will struggle on and do what it can no matter what. Later on, ggpyjobs can choose to freak out or not when it encounters missing data.

**Comment by GraylinKim** [comment]
d71f67bfc0794cd03079777b97e67cd0a212a138 makes sure that s2gs parsing never throws localization issues except when in debug mode. Instead it will fill in "Unknown" for the translated value.

If we decide that we need to make sure certain things loaded into the DB cannot be Unknown then we can add checks into `populateDBFromSummary` and log the issues as necessary. With this patch no changes need to be made to `ggpyjobs` and all tests are now passing.
