### ISSUE TITLE
Is there any way to know the saved camera locations people use like on f1,f2,3 etc

### ISSUE THREAD

**Issue by AlexThomas90210** [ggtracker/sc2reader#203]
Looking for a way to get the camera location saved events, Would be nice too to know when they are used, however, I can figure that one out outside the scope of sc2reader, but really need to know when a camera location is saved.

**Comment by StoicLoofah** [comment]
Sorry, I'm not familiar enough with the contents of the replays to know how to do this, but maybe someone else can jump in!

**Comment by cclauss** [comment]
Search this repo for `camera`:
https://github.com/search?q=repo%3Aggtracker%2Fsc2reader+camera&type=code

**Comment by AlexThomas90210** [comment]
I see, So right now looks like sc2reader just has camera movement events and not camera save events.

Looks like the s2protocol has the camera save event defined here and nothing for using these camera locations: https://github.com/Blizzard/s2protocol/blob/e6dfb2cea7ef0d34199d3df2f2cbebd7ddcd7960/json/protocol92440.json#L5760
 
 Just adding this for context:
To try figure out if a camera location hotkey is used I guess I would need to
1. Save the saved location coordinates
2. Check whenever a camera moved to any of the saved coordinates, when it does, make sure all the following are true:
- The user did not double tab a hotkey to center at that units coordinates (like double tap 4)
- The user didn't pan to the coordinate
- The user didn't just click the minimap
If all are true, then the user tapped the hotkey for that saved location.

I am not super familiar with the internals of sc2reader and how to add new events but I can probably just use mpyq directly for my use case.

Thank you
