### ISSUE TITLE
UpdateTargetPointCommandEvent not working

### ISSUE THREAD

**Issue by ccopland94** [ggtracker/sc2reader#27]
The UpdateTargetPointCommandEvent is not being caught, despite there being some code/attempt to do so. I have a fix I implemented on my local copy, but I wanted to make the issue known. Will likely create a pull request with the changes. They are small and shouldn't break anything existing.

**Comment by ccopland94** [comment]
Created the pull request in #28

**Comment by dsjoerg** [comment]
Fixed in PR #28
