### ISSUE TITLE
Does mpyq need to be added to requirements.txt?

### ISSUE THREAD

**Issue by cclauss** [ggtracker/sc2reader#48]
I could not get the unittests to pass without __pip install mpyq__.

Is __mpyq__ used at runtime or is it only used in the unittests?

**Comment by dsjoerg** [comment]
It's used at runtime: https://github.com/ggtracker/sc2reader/blob/155ae25b7ba335e7baf5337ec4b533ad1df1b5ab/sc2reader/resources.py#L253

`requirements.txt` is not well maintained.  `setup.py` has different logic for which packages are needed.

**Comment by cclauss** [comment]
Should we remove requirements.txt?

**Comment by dsjoerg** [comment]
The README.rst suggest multiple installation options, including `pip install sc2reader`.  Doesn't `pip` use `requirements.txt`?  I wouldn't want to completely break pip installation for people who are doing it.  I would say fix it rather than remove it.

**Comment by StoicLoofah** [comment]
Fixed in #47
