### ISSUE TITLE
LOTV update: timescale

### ISSUE THREAD

**Issue by j4p3** [ggtracker/sc2reader#6]
Replays should be analyzed with the new LOTV real time, instead of Blizz time. [bug]

**To reproduce**:
1. Run any replay

**Expected**:
- Replay length corresponds to number of elapsed minutes/seconds (or hours if you're playing mech)

**Actual**:
- Replay length off by 40% due to normal/faster game speed correction

**Comment by dsjoerg** [comment]
This issue was moved to ggtracker/ggtrackerstack#14
