### ISSUE TITLE
Restore tracker events in anonymized replays

### ISSUE THREAD

**Issue by StoicLoofah** [ggtracker/sc2reader#74]
In #61 @lfricken identified that tracker events were missing in the replay pack given by Blizzard. Figure out how to restore those events.

See #61 for the existing discussion

**Comment by dneise** [comment]
Hello, I believe the tracker events are simply completely missing in the files:

```
18:33 $ mpyq -t ../blizzard_replay_pack/00005c39bf6a3a7a2feabe753de18b497aff2fe9837a7ca1e2e54df25547474b.SC2Replay 
hash_entry MPQHashTableEntry(hash_a=4251285776, hash_b=1318820007, locale=0, platform=0, block_table_index=11)
Files
-----
replay.attributes.events       2037 bytes
replay.details.backup           542 bytes
replay.game.events            23676 bytes
replay.gamemetadata.json        631 bytes
replay.initData.backup         3705 bytes
replay.load.info                 52 bytes
```

So by restoring the tracker events you do not mean: "find and read them" but rather have a game engine re-run the replay and re-create the tracker events?
