### ISSUE TITLE
continous integration testing?

### ISSUE THREAD

**Issue by dneise** [ggtracker/sc2reader#80]
Hey there! Great work!

I just stumbled over this repo while trying to gather some statistics from my own replays.
Looking at #78 I was wondering if you guys would consider setting up automatic testing using for example https://travis-ci.org/ or so. It's free for open source projects. 

Continuous testing means, upon certain events (e.g. for every new pull request or once every day) a machine in the cloud downloads and installs your repo and executes the tests.

This makes for example reviewing new PRs very easy for you, since you can be sure a new feature does not break any existing functionality and you can concentrate more on the new feature itself. 

Something like a daily check can ensure that your project still works, even if for half a year no person executed the tests. This can prevent you from bad surprises, where you look for the source of an error for hours, while actually some 3rd party library changed and you did not notice.

Also I've seen you  support 5 Python versions: 2.7, 3.4 3.5, 3.6 and 3.7. automated testing could install and execute the tests on all of these Pythons for you every day and make sure everything still works, even for 2.7.

I do not ask this just for the fun of it. I was reading through the code and had the impression some stuff could be improved, but I would not like to bother you guys with PRs, as long as there are no tests, which can show, that I did not break anything.

**Comment by cclauss** [comment]
CircleCI tests are run on every pull request:
* https://github.com/ggtracker/sc2reader/blob/upstream/.circleci/config.yml

CircleCI is quite like Travis CI.

**Comment by dneise** [comment]
Ah I totally missed that. Thanks a lot

**Comment by cclauss** [comment]
Please propose new tests if you see a way that we can improve our resiliency.

**Comment by dneise** [comment]
Well I think daily tests might have spotted the issue in #78. So maybe running not only on each new PR but also days or weekly might be good.

**Comment by StoicLoofah** [comment]
I would be okay with doing daily builds and to configure circle ci for that.
