### ISSUE TITLE
where to see the data?

### ISSUE THREAD

**Issue by kaiwangsim** [ggtracker/sc2reader#90]
hello guys, 

i'm fresh of python and can you tell me after i load the replay, there is not output, where can i see the data of the replay?

cheers,

**Comment by StoicLoofah** [comment]
The data should be available on the returned object when you load a replay. Check out this tutorial about roughly how that works https://miguelgondu.github.io/python/ai/video%20games/2018/09/04/a-tutorial-on-sc2reader-events-and-units.html

I have to admit that there isn't much documentation about how to find specific things, so if you have more specific questions, you can ask here.

**Comment by StoicLoofah** [comment]
Closing this for now since there was no followup. Feel free to re-open if there's more discussion
